### ISSUE TITLE
Update for Piwigo 11.2?

### ISSUE THREAD

**Issue by DouglasAlden** [Piwigo/piwigo-openstreetmap#192] opened 2021-02-01 20:01 UTC
Are there any plans in the works to update the extension to support the latest version of Piwigo 11.2?

**Comment by jdbonjour** [comment] 2021-02-23 08:02
Very good plugin, thanks. But yes, it should be certified for  Piwigo 11.x

**Comment by bru500** [comment] 2021-02-23 21:26
Yes, updated Piwigo to 11.x. Now it looks a bit sad, because OpenStreetMap got disabled..
Great plugin, thank you!

**Comment by willemjaap** [comment] 2021-02-28 08:51
agree; if I can be of assistance in coding, please let me know

**Comment by zero0cool0** [comment] 2021-03-04 13:54
I took a leap and activated the plugin, it seems to work but is still showing as incompatible. Like @willemjaap I'm more than happy to help with the coding to get this compatible again.

**Comment by Murdock-droid** [comment] 2021-03-14 02:14
@zero0cool0 Thanks for giving it a shot. I also backed up everything, did the update, and activated the plugin and it does seem to be working.  I started looking through the code to see how Piwigo is determining that the plugin is incompatible. I was hoping to find a MAX_COMPAT_VER_NO somewhere. So far, no luck.

**Comment by haschmich** [comment] 2021-03-25 20:42
Might be worth asking in the Piwigo Forum. Would do it myself but cannot login currently because passwort reset does not work and the admin does not answer.

**Comment by jdbonjour** [comment] 2021-04-30 06:42
The development of Piwigo is progressing very fast, these times (version 11.4.0 has just been released). It's boring that users of the piwigo-openstreetmap plugin are still stuck with Piwigo version 2.x. Does @xbgmsharp plan to do anything to make this plugin compatible with Piwigo 11.x ?

**Comment by dmfisch** [comment] 2021-05-11 07:42
I would love to keep this plugin going,
But I can't code and just give praises!
Best regards!
David
https://map-mayenfisch.com/map/

**Comment by xplosionmind** [comment] 2021-06-06 07:35
> I would love to keep this plugin going,
> But I can't code and just give praises!

+1!

I would love this plugin to continue to be maintained!

Best,
T

**Comment by jose1711** [comment] 2021-06-06 22:54
Please let me understand. The issue is (or may not be) with the plugin itself - only with the way how Piwigo is determining the compatibility. Is that correct?

**Comment by bru500** [comment] 2021-06-07 04:39
@jose1711 Yes. The Plugin got automatically deactivated with the update to Piwigo 11. Since I found out, that I could simply activate it again, it works as before on our site. Only it is marked as not compatible.

**Comment by Murdock-droid** [comment] 2021-06-29 03:45
Ok. Since the plugin is functioning correctly, I wanted to learn what was making Piwigo determine that the plugin might be incompatible. So I started with [THIS](url) post, and then found [THIS](https://piwigo.org/doc/doku.php?id=dev:changes_in_2.11#plugin_has_settings) post that explained what was different with this version.  So, it seems to be the admin menu change that is tripping the indicator to say that the plugin is incompatible. 

I opened up the "main.inc.php" in the plugin folder, and added "Has Settings: webmaster" to the end of plugin name/description block at the top, and saved it. Then went to test it...and it didn't work...or so I thought. Because...now that I am looking at it weeks later...the warning message and alert icon are gone. I think I may have had to clear a cache or something. All I know is...they are gone now. (I am glad I didn't close those tabs weeks ago!)

Before: 
![image](https://user-images.githubusercontent.com/59328366/123733710-fc3db400-d869-11eb-938d-5de2ecbc4659.png)

After:
![image](https://user-images.githubusercontent.com/59328366/123733769-27280800-d86a-11eb-9c5d-3045250acaab.png)

Here is the section of code I touched: 
(Note the "_Has Settings..._" at the bottom...that was what I added.)
```
<?php
/*
Plugin Name: OpenStreetMap
Version: 2.9.a
Description: OpenStreetMap integration for piwigo
Plugin URI: http://piwigo.org/ext/extension_view.php?eid=701
Author: xbmgsharp
Author URI: https://github.com/xbgmsharp/piwigo-openstreetmap
Has Settings: webmaster
*/
```

I hope this helps others,
Murdock

**Closed** 2021-10-16 08:11 UTC
